service: eventHandlerSlack

provider:
    name: aws
    stage: prod
    runtime: nodejs14.x
    region: us-east-1
    timeout: 3
    memorySize: 256
    environment:
        SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
        NEW_MEMBERS_WH: ${env:NEW_MEMBERS_WH}
        LOG_WH: ${env:LOG_WH}

functions:
    incoming:
        handler: events.incoming
        events:
            - http:
                path: incoming
                method: POST
